site_name: 'SOPS Documentation'
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust

site_url: https://sops.pages.dev/

nav:
  - Home: 'README.md'
  - Change Log: 'CHANGELOG.md'

plugins:
  - search
