name: "Docs"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    # Only consider changes to documentation
    paths:
      - '.github/workflows/docs.yaml'
      - '**/*.md'
      - '**/*.rst'
      - '**/*.txt'
  schedule:
    - cron: '25 6 * * 3'

permissions:
  contents: read

jobs:
  documentation:
    name: Lint RST and MD files
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.0.0

      - name: Install rstcheck and markdownlint
        run: |
          pip install rstcheck
          sudo gem install mdl

      - name: Run rstcheck on all RST files
        run: make checkrst

      - name: Run mdl on all MD files
        run: make checkmd

      - run: |
          pip install sphinx
          mkdir -p _site
          rst2html.py README.rst _site/index.html

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
    